version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.3.3
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build 
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $AUTH | base64 -d  > ./account.json
              export $project_id=$PROJECT_ID
              packer build build.json
            fi
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: GCP
